########################
# General Settings     #
########################
custom-money-format: true #If this is enabled the plugin cost enchantment values will be converted to K,M,B,T,Q,QQ,S,SS,O,N,D.
use-default-level: false  #Disable minecraft vanilla enchantment limit.
custom-levels-limit:
 looting: 150
 unbreaking: 150
 fire_aspect: 150
 sharpness: 150
 knockback: 150
 vanishing_curse: 150
 mending: 150
 sweeping_edge: 150
########################
# Prices               #
########################
looting:
  price: 100
  multiplicator: 2
unbreaking:
  price: 200
  multiplicator: 3
fire-aspect:
  price: 300
  multiplicator: 5
sharpness:
  price: 700
  multiplicator: 6
knockback:
  price: 1000
  multiplicator: 7
curse-of-vanishing:
  price: 2000
  multiplicator: 8
mending:
  price: 5000
  multiplicator: 9
sweeping-edge:
  price: 20000
  multiplicator: 11
rename-sword:
  price: 50