name: UpgradeSword
version: '2.1-SNAPSHOT'
main: net.dexterr.plugins.swordupgrade.Main
depend: [Vault]
api-version: '1.21'
commands:
  upgradesword:
    description: Reload the UpgradeSword configuration
    usage: /<command> reload
    permission: upgradesword.use
    permission-message: You don't have permission to use this command.